server:
  port: 8080

spring:
  h2:
    console:
      enabled: true  # H2 Console? ???? ?? (H2 Console? H2 Database? UI? ????? ??)
      path: /h2-console  # H2 Console? Path
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MYSQL
    username: user
    password: user
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  mvc:
    problemdetails:
      enabled: true
  docker:
    compose:
      file: ./docker/docker-compose.yml
      lifecycle-management: start_only

infcon:
  location: coex
  date: 2023-08-15
  url: https://inflearn.com/conf/infcon-2023