server:
  port: 12345

spring:
  h2:
    console:
      enabled: true  # H2 Console? ???? ?? (H2 Console? H2 Database? UI? ????? ??)
      path: /h2-console  # H2 Console? Path
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MYSQL
    username: user
    password: user
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  mvc:
    problem details:
      enabled: true
    path match:
      matching-strategy: ant_path_matcher
  docker:
    compose:
      file: ./docker/docker-compose.yml
      lifecycle-management: start_only
  springdoc:
    default-consumes-media-type: application/json
    default-produces-media-type: application/json
    swagger-ui:
      enabled: true
      tags-sorter: alpha
      server: http://localhost:12345/
      path: /swagger-ui.html
    api-docs:
      enabled: true
      path: /v3/api-docs
  server:
    servlet:
      context-path: /
      encoding:
        force: true